added files
SkylineCommunications/SLC-AS-EVSCerebrum pull request #2
Opened 2024-12-19 16:13 UTC by GillesVH

review request catalog item EVS Cerebrum

2024-12-19 20:54 UTC, jarno-lernou commented
@EdithLansens, let me take up the first review cycle please.

2024-12-20 12:44 UTC, jarno-lernou requested changes
Overall good, some small feedback.

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/manifest.yml
This file should reside in the root folder of the repository in order for the (current) CI/CD tools to work.

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/manifest.yml
> +source_code_url: 'https://github.com/SkylineCommunications/SLC-AS-EVSCerebrum'
This field can be left out as this will be automatically resolved by CI/CD.

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/manifest.yml
> +tags:
This field can be left out as this will be automatically resolved by CI/CD through the GitHub Repository topics.
I would also remove 'EVS Cerebrum' as it's identical to the name of the catalog item. I would add though some more technical market terms, such as 'Broadcast', (IP or SDI)'Workflow', 'Broadcast Control System', 'Routing', 'Control Panel'

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/manifest.yml
> +tags:
Do note, this is part of the Product Solution, making sure you align with market terminology.

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/manifest.yml
> +short_description: 'Low code app that enables you to select the router level, source, and destination to establish a route connection.'
This field can be left out as this will be automatically resolved by CI/CD through the GitHub Repository short description.

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/readme.md
> +Unlock the full potential of your operations with the powerful integration of EVS Cerebrum and DataMiner. DataMiner establishes connectivity, setting crosspoints between pre-reserved resources—ideal
the hyphen probably needed a space?

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/readme.md
> +1. Look up the [*EVS Cerebrum package*](https://catalog.dataminer.services/details/334a4bfd-9a4a-4aea-8169-c4a3b754a683).
This step can be left out.

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/readme.md
This should be located in the root of the repository.

2024-12-20 12:44 UTC, jarno-lernou commented on Documentation/readme.md
> +- **Easy-to-use**: With just a few clicks, a route connection can be established.
Key Features should really address the needs of the operations. I would indicate for example 'Router Control Panel' and then use the 'easy-to-use' in bold in your sentence.

2024-12-24 11:15 UTC, GillesVH commented
Applied feedback from Jarno

2024-12-24 11:28 UTC, EdithLansens reviewed
I did not have write access, so I was unable to make changes directly to the *README.md* file. Could you approve these suggestions, @GillesVH?

2024-12-30 14:48 UTC, merged